/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VoiceRouteImport } from './routes/voice'
import { Route as ReadinessRouteImport } from './routes/readiness'
import { Route as HelloRouteImport } from './routes/hello'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ReadinessIndexRouteImport } from './routes/readiness.index'
import { Route as ReadinessWeatherRouteImport } from './routes/readiness.weather'
import { Route as ReadinessPassportRouteImport } from './routes/readiness.passport'
import { Route as ReadinessGapRouteImport } from './routes/readiness.gap'
import { Route as ReadinessForwardRouteImport } from './routes/readiness.forward'

const VoiceRoute = VoiceRouteImport.update({
  id: '/voice',
  path: '/voice',
  getParentRoute: () => rootRouteImport,
} as any)
const ReadinessRoute = ReadinessRouteImport.update({
  id: '/readiness',
  path: '/readiness',
  getParentRoute: () => rootRouteImport,
} as any)
const HelloRoute = HelloRouteImport.update({
  id: '/hello',
  path: '/hello',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReadinessIndexRoute = ReadinessIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ReadinessRoute,
} as any)
const ReadinessWeatherRoute = ReadinessWeatherRouteImport.update({
  id: '/weather',
  path: '/weather',
  getParentRoute: () => ReadinessRoute,
} as any)
const ReadinessPassportRoute = ReadinessPassportRouteImport.update({
  id: '/passport',
  path: '/passport',
  getParentRoute: () => ReadinessRoute,
} as any)
const ReadinessGapRoute = ReadinessGapRouteImport.update({
  id: '/gap',
  path: '/gap',
  getParentRoute: () => ReadinessRoute,
} as any)
const ReadinessForwardRoute = ReadinessForwardRouteImport.update({
  id: '/forward',
  path: '/forward',
  getParentRoute: () => ReadinessRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/hello': typeof HelloRoute
  '/readiness': typeof ReadinessRouteWithChildren
  '/voice': typeof VoiceRoute
  '/readiness/forward': typeof ReadinessForwardRoute
  '/readiness/gap': typeof ReadinessGapRoute
  '/readiness/passport': typeof ReadinessPassportRoute
  '/readiness/weather': typeof ReadinessWeatherRoute
  '/readiness/': typeof ReadinessIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/hello': typeof HelloRoute
  '/voice': typeof VoiceRoute
  '/readiness/forward': typeof ReadinessForwardRoute
  '/readiness/gap': typeof ReadinessGapRoute
  '/readiness/passport': typeof ReadinessPassportRoute
  '/readiness/weather': typeof ReadinessWeatherRoute
  '/readiness': typeof ReadinessIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/hello': typeof HelloRoute
  '/readiness': typeof ReadinessRouteWithChildren
  '/voice': typeof VoiceRoute
  '/readiness/forward': typeof ReadinessForwardRoute
  '/readiness/gap': typeof ReadinessGapRoute
  '/readiness/passport': typeof ReadinessPassportRoute
  '/readiness/weather': typeof ReadinessWeatherRoute
  '/readiness/': typeof ReadinessIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/hello'
    | '/readiness'
    | '/voice'
    | '/readiness/forward'
    | '/readiness/gap'
    | '/readiness/passport'
    | '/readiness/weather'
    | '/readiness/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/hello'
    | '/voice'
    | '/readiness/forward'
    | '/readiness/gap'
    | '/readiness/passport'
    | '/readiness/weather'
    | '/readiness'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/hello'
    | '/readiness'
    | '/voice'
    | '/readiness/forward'
    | '/readiness/gap'
    | '/readiness/passport'
    | '/readiness/weather'
    | '/readiness/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  HelloRoute: typeof HelloRoute
  ReadinessRoute: typeof ReadinessRouteWithChildren
  VoiceRoute: typeof VoiceRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/voice': {
      id: '/voice'
      path: '/voice'
      fullPath: '/voice'
      preLoaderRoute: typeof VoiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/readiness': {
      id: '/readiness'
      path: '/readiness'
      fullPath: '/readiness'
      preLoaderRoute: typeof ReadinessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hello': {
      id: '/hello'
      path: '/hello'
      fullPath: '/hello'
      preLoaderRoute: typeof HelloRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/readiness/': {
      id: '/readiness/'
      path: '/'
      fullPath: '/readiness/'
      preLoaderRoute: typeof ReadinessIndexRouteImport
      parentRoute: typeof ReadinessRoute
    }
    '/readiness/weather': {
      id: '/readiness/weather'
      path: '/weather'
      fullPath: '/readiness/weather'
      preLoaderRoute: typeof ReadinessWeatherRouteImport
      parentRoute: typeof ReadinessRoute
    }
    '/readiness/passport': {
      id: '/readiness/passport'
      path: '/passport'
      fullPath: '/readiness/passport'
      preLoaderRoute: typeof ReadinessPassportRouteImport
      parentRoute: typeof ReadinessRoute
    }
    '/readiness/gap': {
      id: '/readiness/gap'
      path: '/gap'
      fullPath: '/readiness/gap'
      preLoaderRoute: typeof ReadinessGapRouteImport
      parentRoute: typeof ReadinessRoute
    }
    '/readiness/forward': {
      id: '/readiness/forward'
      path: '/forward'
      fullPath: '/readiness/forward'
      preLoaderRoute: typeof ReadinessForwardRouteImport
      parentRoute: typeof ReadinessRoute
    }
  }
}

interface ReadinessRouteChildren {
  ReadinessForwardRoute: typeof ReadinessForwardRoute
  ReadinessGapRoute: typeof ReadinessGapRoute
  ReadinessPassportRoute: typeof ReadinessPassportRoute
  ReadinessWeatherRoute: typeof ReadinessWeatherRoute
  ReadinessIndexRoute: typeof ReadinessIndexRoute
}

const ReadinessRouteChildren: ReadinessRouteChildren = {
  ReadinessForwardRoute: ReadinessForwardRoute,
  ReadinessGapRoute: ReadinessGapRoute,
  ReadinessPassportRoute: ReadinessPassportRoute,
  ReadinessWeatherRoute: ReadinessWeatherRoute,
  ReadinessIndexRoute: ReadinessIndexRoute,
}

const ReadinessRouteWithChildren = ReadinessRoute._addFileChildren(
  ReadinessRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  HelloRoute: HelloRoute,
  ReadinessRoute: ReadinessRouteWithChildren,
  VoiceRoute: VoiceRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
